#!/bin/bash
GOOS=aix GOARCH=ppc64 go build -o benchbot-aix-ppc64
GOOS=darwin GOARCH=386 go build -o benchbot-darwin-386
GOOS=darwin GOARCH=amd64 go build -o benchbot-darwin-amd64
GOOS=dragonfly GOARCH=amd64 go build -o benchbot-dragonfly-amd64
GOOS=freebsd GOARCH=386 go build -o benchbot-freebsd-386
GOOS=freebsd GOARCH=amd64 go build -o benchbot-freebsd-amd64
GOOS=freebsd GOARCH=arm go build -o benchbot-freebsd-arm
GOOS=freebsd GOARCH=arm64 go build -o benchbot-freebsd-arm64
GOOS=illumos GOARCH=arm64 go build -o benchbot-illumos-arm64
GOOS=js GOARCH=wasm go build -o benchbot.wasm
GOOS=linux GOARCH=386 go build -o benchbot-linux-386
GOOS=linux GOARCH=amd64 go build -o benchbot-linux-amd64
GOOS=linux GOARCH=arm go build -o benchbot-linux-arm
GOOS=linux GOARCH=arm64 go build -o benchbot-linux-arm64
GOOS=linux GOARCH=ppc64 go build -o benchbot-linux-ppc64
GOOS=linux GOARCH=ppc64le go build -o benchbot-linux-ppc64le
GOOS=linux GOARCH=mips go build -o benchbot-linux-mips
GOOS=linux GOARCH=mipsle go build -o benchbot-linux-mipsle
GOOS=linux GOARCH=mips64 go build -o benchbot-linux-mips64
GOOS=linux GOARCH=mips64le go build -o benchbot-linux-mips64le
GOOS=linux GOARCH=riscv64 go build -o benchbot-linux-riscv64
GOOS=linux GOARCH=s390x go build -o benchbot-linux-s390x
GOOS=netbsd GOARCH=s390x go build -o benchbot-netbsd-386
GOOS=netbsd GOARCH=amd64 go build -o benchbot-netbsd-amd64
GOOS=netbsd GOARCH=arm go build -o benchbot-netbsd-arm
GOOS=netbsd GOARCH=arm64 go build -o benchbot-netbsd-arm64
GOOS=openbsd GOARCH=386 go build -o benchbot-openbsd-386
GOOS=openbsd GOARCH=arm64 go build -o benchbot-openbsd-amd64
GOOS=openbsd GOARCH=arm go build -o benchbot-openbsd-arm
GOOS=openbsd GOARCH=arm64 go build -o benchbot-openbsd-arm64
GOOS=plan9 GOARCH=386 go build -o benchbot-plan9-386
GOOS=plan9 GOARCH=amd64 go build -o benchbot-plan9-amd64
GOOS=plan9 GOARCH=arm go build -o benchbot-plan9-arm
GOOS=solaris GOARCH=arm go build -o benchbot-solaris-amd64
GOOS=windows GOARCH=386 go build -o benchbot-win-386.exe
GOOS=windows GOARCH=amd64 go build -o benchbot-win-amd64.exe
GOOS=windows GOARCH=arm go build -o benchbot-win-arm.exe

